Django-course/mproject/developer/urls.py
from django.urls import path
from . import views
from .views import DevDetailVue,IndexView

app_name = 'developer'
urlpatterns = [
path('', IndexView.as_view(), name='index'),
path('<int:pk>',  DevDetailVue.as_view(), name='detail'),
path('create', views.create, name='create'),
path('delete/<int:id>', views.delete, name='delete'),
]

Django-course/mproject/home/urls.py
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
path('', views.HomeView.as_view(), name='home'),
]

Django-course/mproject/mproject/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
path('developer/', include('developer.urls')),
path('task/', include('task.urls')),
path('admin/', admin.site.urls),
path('', include('home.urls')),
path('accounts/', include('django.contrib.auth.urls')),
]

Django-course/mproject/task/urls.py
from django.urls import path
from . import views
from .views import IndexView

app_name = 'task'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('create', views.create, name='create'),
    path('delete/<int:task_id>', views.delete, name='delete'),
]

Django-course/mproject/developer/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db import models

class Developer(AbstractUser): 
    first_name = models.CharField("first name", max_length=200)
    last_name = models.CharField(max_length=200)
    user_name = models.CharField(max_length=50)
    REQUIRED_FIELDS=['first_name', 'last_name']
    def is_free(self):
        return self.tasks.count() == 0

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
        
    is_free.boolean = True 
    is_free.short_description = 'Is free' 

Django-course/mproject/home/models.py
from django.db import models

# Create your models here.

Django-course/mproject/task/models.py
from django.db import models
from developer.models import Developer

class Task(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    assignee = models.ForeignKey(Developer, related_name="tasks", on_delete=models.SET_NULL, null=True, verbose_name="assignee")
    def __str__(self):
        return f"{self.title} ({self.description})"
    class Meta:
        permissions = [
            ('task_management', 'Can create, assign and delete tasks'),
        ]

Django-course/mproject/developer/forms.py
from django import forms
from .models import Developer
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from task.models import Task



class DeveloperForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username','email')
        
class DeveloperChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'username','email')


#...
class ShortDeveloperForm(forms.ModelForm):
    class Meta:
        model = Developer
        fields = ['first_name', 'last_name', 'username','password']
#...


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'assignee']

Django-course/mproject/task/forms.py
from django import forms
from .models import Task
class TaskForm(forms.ModelForm): 
    class Meta: 
        model = Task
        fields = ['title', 'description', 'assignee']

Django-course/mproject/developer/views.py
from django.shortcuts import render, get_object_or_404
from .models import Developer
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import TaskForm,ShortDeveloperForm#,DeveloperForm
from django.views.generic import DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin


# def index(request):
#     context = {
#         'developers': Developer.objects.all(),
#         'form': DeveloperForm,
#     }
#     return render(request, 'developer/index.html', context)
#
# def detail(request, developer_id):
#     developer = get_object_or_404(Developer, pk=developer_id)
#     return render(request, 'developer/detail.html', {'developer': developer})


def create(request):
    form = ShortDeveloperForm(request.POST)
    if form.is_valid():
        Developer.objects.create(
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
        )
    return HttpResponseRedirect(reverse('developer:index'))


def delete(request,id):
    developer = get_object_or_404(Developer, pk=id)
    developer.delete()
    return HttpResponseRedirect(reverse('developer:index'))


class IndexView(LoginRequiredMixin,ListView):
    model = Developer
    template_name = "developer/index.html"
    context_object_name = 'developers'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] =  ShortDeveloperForm 
        return context


class DevDetailVue(LoginRequiredMixin,DetailView):
    model = Developer
    template_name = 'developer/detail.html'
    def get_context_data(self, **kwargs):
        context = super(DevDetailVue, self).get_context_data(**kwargs)
        form = TaskForm(initial={'assignee': get_object_or_404(Developer, pk=self.kwargs['pk'])})
        form.fields['assignee'].disabled = True
        context['form'] = form
        return context

Django-course/mproject/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "home/index.html"

Django-course/mproject/task/views.py
from django.shortcuts import render, get_object_or_404

from task.forms import TaskForm
from .models import Task
from developer.models import Developer
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

def index(request):
    return render(request, 'task/index.html')

def delete(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    task.delete()
    return HttpResponseRedirect(reverse('task:index'))

def create(request):
    form = TaskForm(request.POST)
    if form.is_valid():
        Task.objects.create(
            title=form.cleaned_data['title'],
            description=form.cleaned_data['description'],
            assignee =form.cleaned_data['assignee'],
        )
    return HttpResponseRedirect(reverse('task:index'))

class IndexView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    model = Task
    template_name = "task/index.html"
    context_object_name = 'tasks'
    permission_required = 'task.task_management' 
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['form'] = TaskForm(initial={'assignee': Developer.objects.first()})
        return context

Django-course/mproject/developer/templates/developer/_base.html
{% extends "_base.html" %}

{% block title %}GProject - Gestion des Developers {% endblock title %}
    

{% block menu-script %}
$("#nav-home").removeClass('active')
$("#nav-dev").addClass('active')
$("#nav-task").removeClass('active')
{% endblock menu-script %}

Django-course/mproject/developer/templates/developer/_create_dev_modal_.html
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-dev-modal">Add dev</button>

<div class="modal fade" id="add-dev-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">New developer</h4><button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'developer:create' %}" method="post">
                    {% load crispy_forms_tags %} 
                    {% csrf_token %}
                    {{ form|crispy }} 
                    <div>
                        <button class="btn btn-primary" type="submit">Créer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

Django-course/mproject/developer/templates/developer/detail.html
{% extends "developer/_base.html" %}

{% block title %} Détail - {{ developer.first_name }} {{developer.last_name }} {% endblock title %}
{% block content %}
<div class="jumbotron" style="height:150px">
    <form action="{% url 'developer:delete' developer.id %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="close"><i class="fa-sharp fa-solid fa-trash"></i></button>
    </form>

    <h1>{{ developer.first_name }} {{ developer.last_name }}
    </h1>
    <p>{{ developer.tasks.all|length }}
        tâche{{developer.tasks.all|length|pluralize}}
        assignée{{developer.tasks.all|length|pluralize}}.</p>
</div>
<div class="container-sm">
    {% if not developer.is_free %}
    <ul class="list-group">
        {% for task in developer.tasks.all %}
        <li class="list-group-item">
            <strong>{{ task.title }}!</strong> {{ task.description }}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div class="alert alert-danger">
        Aucune tâche n'est assignée à {{ developer.first_name }}.
    </div>
    {% endif %}
</div>
{% include 'task/_create_task_modal_.html' %}
{% endblock content %}

Django-course/mproject/developer/templates/developer/index.html
{% extends "developer/_base.html" %}

{% block title %} Liste des dévelopeurs {% endblock title %}

{% block content %}
{% if developers %}
<div class="container-sm l-3 d-flex flex-wrap border">
    {% for dev in developers %}
    <div class="card bg-primary m-2 p-1 rounded-lg" style="width:300px">
        <div class="card-title">
            {{ dev.first_name }} {{ dev.last_name }}
        </div>
        <div class="card-body">
            {{ dev.tasks.all|length }}
             tâche{{developer.tasks.all|length|pluralize}} 
        </div>
        <div class="card-footer">
            <a href="{% url 'developer:detail' dev.id %}" class="btn btn-outline-light">Détails</a>
        </div>
    </div>
    {% endfor %}
</div>

{% else %}
<div class="container m-4">
    <alert class="alert alert-warning">Il n'y a aucun dévelopeur enregistré</alert>
</div>
{% endif %}

{% include 'developer/_create_dev_modal_.html' %}

{% endblock content %}

Django-course/mproject/home/templates/home/index.html
{% extends "_base.html" %}
{% block content %}
    {% if user.is_authenticated %}
        <div class="p-1 m-3 bg-light">
            <p class="float-right"><a href={% url 'logout' %}><i class="fa fa-sign-out"></i></a></p>
            <h1>{{ user.first_name }} {{ user.last_name }}</h1>
        </div>
        <div class="container-sm">
            {% if user.tasks.all|length %}
                <ul class="list-group fluid">
                {% for task in user.tasks.all %}
                    <li class="list-group-item">
                        <strong>{{ task.title }}</strong>
                        {{ task.description }}
                    </li>
                {% endfor %}
                </ul>
            {% else %}
                <alert class="alert alert-warning">No Tasks</alert>
            {% endif %}
        </div>
    {% else %}
        <h1>Coucou toi !</h1>
        <a href={% url 'login' %}>Log in</a>
    {% endif %}
{% endblock content%}

Django-course/mproject/task/templates/task/_base.html
{% extends "_base.html" %}

{% block title %}GProject - Gestion des tâches{% endblock title %}

{% block menu-script %}
    $("#nav-home").removeClass('active')
    $("#nav-dev").removeClass('active')
    $("#nav-task").addClass('active')
{% endblock menu-script %}

Django-course/mproject/task/templates/task/_create_task_modal_.html
{% if perms.task.task_management %}
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#add-dev-modal">Add task</button>

<div class="modal fade" id="add-dev-modal">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">New Task</h4><button type="button" class="close" data-dismiss="modal"><i class="fa fa-close"></i></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'task:create' %}"  id="create-form" onsubmit="$('#create-form *').removeAttr('disabled');" method="post">
                    {% load crispy_forms_tags %} 
                    {% csrf_token %}
                    {{ form|crispy }} 
                    <div>
                        <button class="btn btn-primary" type="submit">Créer</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endif %}

Django-course/mproject/task/templates/task/index.html
{% extends "task/_base.html" %} 

{% block title %}MProject - tâches{% endblock title%}
{% block content %}
    {% if tasks %}
        <div class="container-sm l-3 d-flex flex-wrap border">
            {% for task in tasks %}
                <li class="list-group-item">
                    {{ task.title }}
                    {% if task.assignee %}
                        <span>(assignée à {{ task.assignee.first_name }})</span>
                    {% else %}
                        <span>(non assignée)</span>
                    {% endif %}
                    <form action="{% url 'task:delete' task.id %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" class="close"><i class="fa-sharp fa-solid fa-trash"></i></button>
                    </form>
                </li>
            {% endfor %}
        </div>
    {% else %}
        <div class="container m-4">
            <alert class="alert alert-warning">Il n'y a aucune tâche enregistrée</alert>
        </div>
    {% endif %}
    {% include 'task/_create_task_modal_.html' %}
{% endblock content %}

Django-course/mproject/templates/_base.html
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    
    <title>{% block title %}MProject{% endblock title %}</title>
</head>

<body>
    <div class="p-3 bg-primary">
        <h1 class="display-1">MProject</h1>
        <h2>Un site web de gestion de tâches</h2>
    </div>
    <nav class="navbar navbar-expand-sm bg-primary navbar-dark bordertop border-white">
        <ul class="navbar-nav">
            <li id="nav-home" class="nav-item">
                <a class="nav-link" href="{% url 'home:home' %}"><i class="fa fa-home"></i>
                </a>
            </li>
            <li id="nav-dev" class="nav-item active">
                <a class="nav-link" href="{% url 'developer:index' %}">Developers</a>
            </li>
            <li id="nav-task" class="nav-item">
                <a class="nav-link" href="{% url 'task:index' %}">Tasks</a>
            </li>
        </ul>
    </nav>

    {% block content %}
    {% endblock content %}
    <script>
        {% block menu-script %}
            $("#nav-home").addClass('active')
            $("#nav-dev").removeClass('active')
            $("#nav-task").removeClass('active')
        {% endblock menu-script %}
        </script>
        
</body>

</html>