Django-course/Odoo_Django/realtor_client/odoo_appartement_offer/urls.py
from django.urls import path
from . import views

app_name = 'odoo_offer'
urlpatterns = [
path('', views.index, name='catalogue'),
path('updateOffer', views.updateOffer, name='updateOffer'),
]

Django-course/Odoo_Django/realtor_client/odoo_connection/urls.py
from django.urls import path
from . import views

app_name = 'odoo_connection'
urlpatterns = [
path('', views.index, name='index'),

]

Django-course/Odoo_Django/realtor_client/realtor_client/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('odoo_connection.urls')),
    path('catalogue/', include('odoo_appartement_offer.urls')),
]

Django-course/Odoo_Django/realtor_client/odoo_appartement_offer/models.py
from django.db import models
from odoo_connection.odooBackend import OdooBackend
from odoo_connection.models import OdooUser
# Create your models here.
class Appartement(models.Model):
    
    def getAppartements():
        backend = OdooBackend()
        uid = OdooUser.objects.get().odoo_id
        password = OdooUser.objects.get().password
        data = backend.model.execute_kw(backend.db_odoo,uid,password,"realtor.appartement","search",[[]],)
        appartements = backend.model.execute_kw(backend.db_odoo,uid,password,"realtor.appartement", 'read',[data], {'fields': ['name', 'desc','image','date_disponibility','minimal_price','buyer_bid']})

        for appartement in appartements:
            products = backend.model.execute_kw(backend.db_odoo,uid,password,'product.product','search', [[['appartement_id', 'ilike', appartement['id']]]])
            details = backend.model.execute_kw(backend.db_odoo,uid,password,'product.product', 'read', [products, ['name', 'free_qty']])
            for detail in details:
                appartement['qte'] = detail['free_qty']
                appartement['details_name'] = detail['name']
        return appartements

    def updateOffer(email,fname,lname,offer,appartement_id):
        backend = OdooBackend()
        uid = OdooUser.objects.get().odoo_id
        password = OdooUser.objects.get().password
        try:
            user_exist = backend.model.execute_kw(backend.db_odoo,uid,password,'res.partner', 'search_count',[[['email', '=', email],['name','=',fname+ " " + lname]]])
            if user_exist == 0:
                partner = backend.model.execute_kw(backend.db_odoo,uid,password, 'res.partner', 'create', [{'name':fname+ " " + lname,'email':email}])
            else:
                partner = backend.model.execute_kw(backend.db_odoo,uid,password,'res.partner', 'search',[[['email', '=', email]]])

            appartement = backend.model.execute_kw(backend.db_odoo,uid,password,"realtor.appartement", 'search',[[['id', '=', appartement_id]]],)
            actual_offer = backend.model.execute_kw(backend.db_odoo,uid,password,"realtor.appartement", 'read',[appartement], {'fields': ['buyer_bid']})
            if actual_offer[0]['buyer_bid'] > int(offer):
                return {'code':'error','message':"The offer is too low, the actual offer is "+str(actual_offer[0]['buyer_bid'])+" €"}
            backend.model.execute_kw(backend.db_odoo,uid,password,"realtor.appartement", 'write', [int(appartement_id), {'buyer_bid': offer,'buyer':partner}])
            return {'code':'success','message':'Offer updated successfully.'}
        except:
            return {'code':'error','message': 'An error occured. Please try again. If the problem persists, contact the administrator.'}
        

Django-course/Odoo_Django/realtor_client/odoo_connection/models.py
from django.db import models

# Create your models here.

class OdooUser(models.Model):
    odoo_id = models.BigIntegerField(primary_key=True)
    password = models.CharField(max_length=255)

Django-course/Odoo_Django/realtor_client/odoo_appartement_offer/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Appartement  
from django.contrib import messages

# Create your views here.

def index(request):
    context = {
        'appartements': Appartement.getAppartements(),
    }
    return render(request, 'odoo_offer/index.html', context)

def updateOffer(request):
    if request.method == 'POST':
        appartement_id = request.POST['appartement_id']
        offer = request.POST['offer']
        lname = request.POST['lname']
        fname = request.POST['fname']
        email = request.POST['email']
        status = Appartement.updateOffer(email,fname,lname, offer,appartement_id)
        if status['code'] == 'error':
            messages.error(request,status['message'])
        else:
            messages.success(request,'Offer updated successfully.')
            
    return redirect('odoo_offer:catalogue')

Django-course/Odoo_Django/realtor_client/odoo_connection/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth import logout
# Create your views here.
def index(request):
    context = {}
    return render(request, 'odoo_connection/index.html', context)

def logout_view(request):
    logout(request)

Django-course/Odoo_Django/realtor_client/odoo_appartement_offer/templates/odoo_offer/_make_offer_modal.html
<div class="modal fade" id="offerModal{{appart.id}}" tabindex="-1" role="dialog" aria-labelledby="offerModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="offerModalLabel">Make offer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                
            </div>
            <div class="modal-body">
                <h6 class="modal-title" id="offerModalLabel">Appartement name - {{appart.name}}</h6>
                <h7 class="modal-title" id="offerModalLabel">Current best offer : {{appart.buyer_bid}}€</h7>
                <br>
                <form action="{% url 'odoo_offer:updateOffer' %}" id="offer_form{{appart.id}}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="i_fname">First name</label>
                        <input type="text" name="fname" class="form-control" id="i_fname" placeholder="Enter your first name" required>

                        <label for="i_lname">Last name</label>
                        <input type="text" name="lname" class="form-control" id="i_lname" placeholder="Enter your last name" required>
                        
                        <label for="i_email">Email</label>
                        <input type="email" name="email" class="form-control" id="i_email" placeholder="Enter your email" required>

                        <label for="i_offer">Offer</label>
                        <input type="number" name="offer" class="form-control" id="i_offer" placeholder="Enter your offer" required  min="1" max="2147483647">

                        <input type="hidden" name="appartement_id" value="{{appart.id}}">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary" form="offer_form{{appart.id}}">Submit offer</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Django-course/Odoo_Django/realtor_client/odoo_appartement_offer/templates/odoo_offer/index.html
{% extends "_base.html" %}
{% block title %}catalogue{% endblock title %}
{% block title_h2 %}Catalogue{% endblock title_h2 %}
{% block bodyContent %}

{% if messages %}
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div id="status-message" class="alert-danger">
                {{ message }}
            </div>
        {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
            <div id="status-message" class="alert-success">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}
    <script>
        $(document).ready(function () {
            setTimeout(function () {
                $('#status-message').fadeOut('fast');
            }, 3000);
        });
    </script>
{% endif %}
<div class="card-deck">
    {% for appart in appartements %}
    <div class="col">
        <div class="card h-100">
            <img src="data:image/jpeg;base64,{{appart.image}}" class="card-img-top" alt="{{appart.details_name}}">
            <div class="card-body">
                <h5 class="card-title">{{appart.name}}</h5>
                <p class="card-text">
                    <span class="font-weight-bold">Description</span> :<br> 
                    {{appart.desc}}
                </p>
            </div>
            <p class="card-text p-2">
                <span class="font-weight-bold">Quantity</span><span> : x{{appart.qte}}
                <br>
                <span class="font-weight-bold">Initial price</span> : {{appart.minimal_price}}€
                <br>
                <span class="font-weight-bold">Best offer</span> : {{appart.buyer_bid}}€
            </p>
            {% if appart.qte == 0 %}
                <a href="#" class="btn btn-danger disabled">Out of stock</a>
            {% else %}
                <a type="button" class="btn btn-primary" data-toggle="modal" data-target="#offerModal{{appart.id}}">Make offer</a>
            {% include 'odoo_offer/_make_offer_modal.html' %}
            {% endif %}
        </div>
    </div>
    {% empty %}
        <div class="container" >
            <h3 class="text-center">No appartement available</h3>
        </div>
    {% endfor %}
</div>
{% endblock bodyContent %}

Django-course/Odoo_Django/realtor_client/odoo_connection/templates/odoo_connection/index.html
{% extends "_base.html" %}
{% block title %}Index {% endblock title %}
{% block title_h2 %}Welcome to Realtor shop{% endblock title_h2 %}
{% block bodyContent %}
    <div class="background">
        <img src="https://img.freepik.com/vecteurs-libre/scene-beau-paysage-urbain-immeuble-grande-hauteur-boutique-rue-parc_1150-48968.jpg?w=2000"
            alt="background" class="img-fluid">
    </div>
{% endblock bodyContent %}

Django-course/Odoo_Django/realtor_client/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title class="text-danger">{% block title %}{% endblock title %}</title>
</head>

<body>
    <h2>{% block title_h2 %}{% endblock title_h2 %}</h2>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand" href="#">Realtor</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'odoo_connection:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'odoo_offer:catalogue' %}">Catalogue</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block bodyContent %}
    {% endblock bodyContent %}
</body>

</html>